/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define RCC_AHB1ENR (*(volatile uint32_t*)0X40023830)
#define RCC_APB2ENR (*(volatile uint32_t*)0x40023844)

#define GPIOC_MODER (*(volatile uint32_t*)0x40020800)
#define GPIOC_AFRL  (*(volatile uint32_t*)0x40020820)

#define USART6_SR (*(volatile uint32_t*)0x40011400)
#define USART6_DR (*(volatile uint32_t*)0x40011404)
#define USART6_BRR (*(volatile uint32_t*)0x40011408)
#define USART6_CR1 (*(volatile uint32_t*)0x4001140C)




void GPIOint(){

	RCC_AHB1ENR |= (1<<2);

	GPIOC_MODER &= ~(3<<12);
	GPIOC_MODER &= ~(3<<14);

	GPIOC_MODER |= (2<<12);
	GPIOC_MODER |= (2<<14);

	GPIOC_AFRL &= ~(0xF<<24);
	GPIOC_AFRL &= ~(0xF<<28);

	GPIOC_AFRL |= (8<<24);
	GPIOC_AFRL |= (8<<28);


}

void usart6int(){
	RCC_APB2ENR |= (1<<5);

	USART6_BRR = 0x683;

	USART6_CR1 |= (1<<3);

	USART6_CR1 |= (1<<2);

	USART6_CR1 |= (1<<13);


}

int main(void)
{
	GPIOint ();
	usart6int();
	char data;

	while(1){

		while(!(USART6_SR & (1<<5)));
	     data = USART6_DR ;

		while(!(USART6_SR & (1<<7)));

		USART6_DR = data;

	}


}
