/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define RCC_AHB1ENR (*(volatile uint32_t*)0x40023830)
#define RCC_APB1ENR (*(volatile uint32_t*)0x40023840)

#define GPIOA_MODER (*(volatile uint32_t*)0x40020000)
#define GPIOA_AFRL  (*(volatile uint32_t*)0x40020020)

#define GPIOD_MODER (*(volatile uint32_t*)0x40020C00)
#define GPIOD_ODR   (*(volatile uint32_t*)0x40020C14)

#define USART2_SR   (*(volatile uint32_t*)0x40004400)
#define USART2_DR   (*(volatile uint32_t*)0x40004404)
#define USART2_BRR   (*(volatile uint32_t*)0x40004408)
#define USART2_CR1   (*(volatile uint32_t*)0x4000440C)

void GPIO_Init(){
	RCC_AHB1ENR |= (1<<0);
	RCC_AHB1ENR |= (1<<3);

	GPIOD_MODER &= ~(3<<24);
	GPIOD_MODER |= (1<<24);

	GPIOA_MODER &= ~((3<<4) | (3<<6));
    GPIOA_MODER |= ((2<<4) | (2<<6));

    GPIOA_AFRL &= ~((15<<8) | (15<<12));
    GPIOA_AFRL |= ((7<<8) | (7<<12));

}

void USART2_Init(){
	RCC_APB1ENR |= (1<<17);
	USART2_BRR = 0x0683;

	USART2_CR1 |= (1<<3);
	USART2_CR1 |= (1<<2);
	//USART_CR1  |= (1<<5);
	USART2_CR1 |= (1<<13);
}

void USART2_SendString(char *str)
{
    while(*str)
    {
    	 while(!(USART2_SR & (1<<7)));

    	    USART2_DR = *str++;



    }
}
int main(void)
{
    GPIO_Init();
    USART2_Init();
    while(1){

    USART2_SendString("UART Implementation\r\n");
    }
}
